name: example-env
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:

  e2e:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

