# Define the name of the GitHub Action workflow
name: Create an ec2 instance
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

# Jobs to be executed in this workflow
jobs:
  # Job for applying the ec2 instance
  apply_ec2:
    # Use the latest Ubuntu runner
    #runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    
    # Execute this step only if the action input is "apply"
    if: ${{ github.event.inputs.action == 'apply' }}
    # Define the steps for this job
    steps:
    
    # checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

